version: '3'

services:
  espeak-wrapper:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
      - HOST=0.0.0.0
      - PORT=5000
      - GUNICORN_BIND=0.0.0.0:5000
      - GUNICORN_WORKERS=2
      - GUNICORN_LOG_LEVEL=info
    volumes:
      - ./:/app
    restart: unless-stopped
